### ISSUE TITLE
401 Unauthorized Error

### ISSUE THREAD

**Issue by sanojsilva** [chrisleekr/yii2-angular-boilerplate#15] opened 2018-08-11 03:33 UTC
I have uploaded the api on to my web server but when i send an get request to the api it gives me back 401 Unauthorized error. When i debug i can see the headers i sent from the frontend are missing in the api. This scenario works well without any issue in my local server with xampp. I have googled for a solution but none of them worked. I think this has to do something with the .htaccess file.

**Comment by chrisleekr** [comment] 2018-08-11 09:30
Hi @sanojsilva 

I don't know how I help you out unless I know how I reproduce the issue. 

Please provide more information or steps.

**Comment by sanojsilva** [comment] 2018-08-11 20:43
hey @chrisleekr

Check out this link my issue is similar to this.
https://github.com/yiisoft/yii2/issues/6631

**Comment by chrisleekr** [comment] 2018-08-12 01:11
@sanojsilva 

That issue must be resolved with my boilerplate as per https://chrislee.kr/wp/2017/01/06/missing-authroization-header-in-request/

I am not sure why you still have an issue with that.

**Comment by sanojsilva** [comment] 2018-08-12 05:05
@chrisleekr  Yes but the problem is $_SERVER['REDIRECT_HTTP_AUTHORIZATION'] doesn't get created even i use the same configuration in .htaccess file

**Comment by chrisleekr** [comment] 2018-08-12 08:27
@sanojsilva umm.. I am not sure then. It must be something different in your server. I cannot reproduce  in my end. Let me know if you find a solution.

**Comment by sanojsilva** [comment] 2018-08-13 16:03
@chrisleekr Okay I'll figure something out thanks

**Closed** 2018-08-25 09:44 UTC

**Comment by sanojsilva** [comment] 2019-01-30 14:45
@chrisleekr Hey, I couldnt find a solution for the above matter. But i found a workaround. I changed the header name to Authorization1 when sending the request with bearer token and i checked for authorization1 header in the serverside. Thatway there is no issue. So i wanted to know that is it ok change the header name from Authorization to Authorization1.
